# https://circleci.com/docs/2.0/language-android
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/bloggie
    docker:
      - image: circleci/android:api-29
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts.kts" }}-{{ checksum  "app/build.gradle.kts.kts" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
#     - run:
##          name: Run Lint
##          command: ./gradlew lintDevDebug
      - run:
          name: Run Spotless
          command: ./gradlew spotlessKotlinCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testDevDebugUnitTest
      - run:
          name: Generate Code Coverage
          command: ./gradlew jacocoTestReportDevDebug

      - run:
          name: Generate Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release
      - store_artifacts:
          path: build/dependencyUpdates
      - codecov/upload:
          flags: unittest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts.kts" }}
