/**
 * Configuration version of all build dependencies
 */
object BuildDependenciesVersions {
    const val KOTLIN = "1.3.61"
    const val APPCOMPAT = "1.1.0"
    const val MATERIAL = "1.0.0"
    const val COROUTINES = "1.3.3"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.1.0"
    const val LIFECYCLE = "2.1.0"
    const val CORE_KTX = "1.1.0"
    const val FRAGMENT_KTX = "1.2.0-alpha02"
    const val CONSTRAIN_LAYOUT = "1.1.3"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0-alpha02"
    const val PAGING = "2.1.1"
    const val TIMBER = "4.7.1"
    const val COIL = "0.8.0"
    const val CRASHLYTICS = "2.10.1"
    const val FIREBASE_ANALYTICS = "17.2.1'"
    const val PLAY_CORE = "1.6.4"
    const val LEAKCANARY = "2.0"
    const val DATABINDING = "3.5.3"
    const val AUTO_SERVICE = "1.0-rc4"
    const val FIREBASE_CORE = "17.2.1"
    const val FIREBASE_AUTH_PLAY_SERVICES = "17.0.0"
    const val FIREBASE_AUTH_UI = "4.0.0"
    const val FIREBASE_AUTH = "19.2.0"
    const val FIREBASE_DATABASE = "19.2.0"
    const val FIREBASE_STORAGE = "19.1.0"
    const val PICASSO = "2.5.2"
    const val LOTTIE = "3.3.1"
    const val KOIN = "1.0.2"
    const val ANNOTATIONS = "1.1.0"

    // Tests
    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.12"
    const val ROBOELECTRIC = "4.3.1"
    const val MOCKITO = "2.2.0"
    const val MOCKK = "1.9.3"
    const val ASSERTJ = "3.14.0"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.1.0"
    const val MOCK_WEB_SERVER = "4.2.2"
}
